var searchData=
[
  ['data',['data',['../classfmt_1_1_basic_string_ref.html#ae9c80502c527437215fe1c11dca8b475',1,'fmt::BasicStringRef::data()'],['../classfmt_1_1_basic_writer.html#a62d1c7b5be9c3580326320d5d178d096',1,'fmt::BasicWriter::data()'],['../classfmt_1_1_format_int.html#a3cad581dde135c51390fd4ebd18d6d1b',1,'fmt::FormatInt::data()']]],
  ['decompose',['decompose',['../group___decomposition.html#gada52dd59060aac8b76281bec95e5f099',1,'diy::decompose(int dim, int rank, const Bounds &amp;domain, const StaticAssigner &amp;assigner, const typename RegularDecomposer&lt; Bounds &gt;::Creator &amp;create, typename RegularDecomposer&lt; Bounds &gt;::BoolVector share_face=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::BoolVector wrap=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector ghosts=typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector(), typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector divs=typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector())'],['../group___decomposition.html#gaf95a2ca4d56a52687be4755d32f956eb',1,'diy::decompose(int dim, int rank, const Bounds &amp;domain, const StaticAssigner &amp;assigner, Master &amp;master, typename RegularDecomposer&lt; Bounds &gt;::BoolVector share_face=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::BoolVector wrap=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector ghosts=typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector(), typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector divs=typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector())'],['../group___decomposition.html#ga8181e8588c444e9cd89fde0f0ffb02dc',1,'diy::decompose(int rank, const StaticAssigner &amp;assigner, Master &amp;master)'],['../group___decomposition.html#gab7b4ad7a00db7746971f9a5a6e593917',1,'diy::decompose(int dim, int rank, const Bounds &amp;domain, const StaticAssigner &amp;assigner, Master &amp;master, const typename RegularDecomposer&lt; Bounds &gt;::Updater &amp;update, typename RegularDecomposer&lt; Bounds &gt;::BoolVector share_face=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::BoolVector wrap=typename RegularDecomposer&lt; Bounds &gt;::BoolVector(), typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector ghosts=typename RegularDecomposer&lt; Bounds &gt;::CoordinateVector(), typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector divs=typename RegularDecomposer&lt; Bounds &gt;::DivisionsVector())']]],
  ['decomposition',['Decomposition',['../group___decomposition.html',1,'']]],
  ['dequeue',['dequeue',['../structdiy_1_1_master_1_1_proxy.html#ad7af65dcf357c32fe550b82a872d8692',1,'diy::Master::Proxy::dequeue(int from, T &amp;x, void(*load)(BinaryBuffer &amp;, T &amp;)=&amp;::diy::load&lt; T &gt;) const '],['../structdiy_1_1_master_1_1_proxy.html#ac89cf0d43ad4eed8e67aabc0b221b745',1,'diy::Master::Proxy::dequeue(int from, T *x, size_t n, void(*load)(BinaryBuffer &amp;, T &amp;)=&amp;::diy::load&lt; T &gt;) const '],['../structdiy_1_1_master_1_1_proxy.html#acc930e3199b1c1cfe5b6e1f853601160',1,'diy::Master::Proxy::dequeue(const BlockID &amp;from, T &amp;x, void(*load)(BinaryBuffer &amp;, T &amp;)=&amp;::diy::load&lt; T &gt;) const '],['../structdiy_1_1_master_1_1_proxy.html#ac6c68a702ad34a9ced41483842d5c1e4',1,'diy::Master::Proxy::dequeue(const BlockID &amp;from, T *x, size_t n, void(*load)(BinaryBuffer &amp;, T &amp;)=&amp;::diy::load&lt; T &gt;) const ']]],
  ['dim',['dim',['../structdiy_1_1_regular_all_reduce_partners.html#a2c548f8b9f13930ac81d2033cade8455',1,'diy::RegularAllReducePartners::dim()'],['../structdiy_1_1_regular_broadcast_partners.html#af15c2f456f39ea39adcde74c2664c308',1,'diy::RegularBroadcastPartners::dim()']]],
  ['dimk',['DimK',['../structdiy_1_1_regular_partners_1_1_dim_k.html',1,'diy::RegularPartners']]],
  ['direction',['Direction',['../structdiy_1_1_direction.html',1,'diy']]],
  ['distance',['distance',['../namespacediy.html#aaa426685de12b51b4a3f283471a0a62b',1,'diy']]],
  ['diy',['diy',['../namespacediy.html',1,'']]],
  ['dummyint',['DummyInt',['../structfmt_1_1internal_1_1_dummy_int.html',1,'fmt::internal']]],
  ['dummystream',['DummyStream',['../structfmt_1_1internal_1_1_dummy_stream.html',1,'fmt::internal']]],
  ['duplicate',['duplicate',['../classdiy_1_1mpi_1_1communicator.html#a5be9b0dcfecee6e8ee54cb934f35af13',1,'diy::mpi::communicator']]],
  ['dynamicassigner',['DynamicAssigner',['../classdiy_1_1_dynamic_assigner.html',1,'diy']]],
  ['dynamicpoint',['DynamicPoint',['../classdiy_1_1_dynamic_point.html',1,'diy']]],
  ['dynamicpoint_3c_20coordinate_20_3e',['DynamicPoint&lt; Coordinate &gt;',['../classdiy_1_1_dynamic_point.html',1,'diy']]],
  ['dynamicpoint_3c_20int_20_3e',['DynamicPoint&lt; int &gt;',['../classdiy_1_1_dynamic_point.html',1,'diy']]],
  ['decomposition',['decomposition',['../md_docs_detail_decomposition.html',1,'']]],
  ['mpi',['mpi',['../namespacediy_1_1mpi.html',1,'diy']]]
];
