var searchData=
[
  ['barrier',['barrier',['../classdiy_1_1mpi_1_1communicator.html#adbc7ea9a65ef0e8e52875511e72aa643',1,'diy::mpi::communicator']]],
  ['basecommand',['BaseCommand',['../structdiy_1_1_master_1_1_base_command.html',1,'diy::Master']]],
  ['basic_5fcstring_5fview',['basic_cstring_view',['../classbasic__cstring__view.html',1,'basic_cstring_view&lt; Char &gt;'],['../classbasic__cstring__view.html#ab464b2378652892cec4716d3e3d475c7',1,'basic_cstring_view::basic_cstring_view(const Char *s)'],['../classbasic__cstring__view.html#a10b92cc0e3e67789601984099b9ed339',1,'basic_cstring_view::basic_cstring_view(const std::basic_string&lt; Char &gt; &amp;s)']]],
  ['basic_5fdata',['basic_data',['../structinternal_1_1basic__data.html',1,'internal']]],
  ['basic_5fdata_3c_3e',['basic_data&lt;&gt;',['../structinternal_1_1basic__data.html',1,'internal']]],
  ['basic_5fformat_5farg',['basic_format_arg',['../classbasic__format__arg.html',1,'']]],
  ['basic_5fformat_5fargs',['basic_format_args',['../classbasic__format__args.html',1,'basic_format_args&lt; Context &gt;'],['../classbasic__format__args.html#a1c7b943f3e4ee3d6864143b5b451969e',1,'basic_format_args::basic_format_args(const format_arg_store&lt; Context, Args...&gt; &amp;store)'],['../classbasic__format__args.html#a6d735ccb56f6c4f64ba1199f223c8a6b',1,'basic_format_args::basic_format_args(const format_arg *args, int count)']]],
  ['basic_5fformat_5fargs_3c_20basic_5fformat_5fcontext_20_3e',['basic_format_args&lt; basic_format_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20basic_5fprintf_5fcontext_20_3e',['basic_format_args&lt; basic_printf_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20format_5fcontext_20_3e',['basic_format_args&lt; format_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20wformat_5fcontext_20_3e',['basic_format_args&lt; wformat_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fcontext',['basic_format_context',['../classbasic__format__context.html',1,'basic_format_context&lt; OutputIt, Char &gt;'],['../classbasic__format__context.html#a545b2e17dfec6a57d19ff8f957b1b4fc',1,'basic_format_context::basic_format_context()']]],
  ['basic_5fformat_5fspecs',['basic_format_specs',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fspecs_3c_20char_5ftype_20_3e',['basic_format_specs&lt; char_type &gt;',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fspecs_3c_20context_3a_3achar_5ftype_20_3e',['basic_format_specs&lt; Context::char_type &gt;',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fformat_5fspecs_3c_20parsecontext_3a_3achar_5ftype_20_3e',['basic_format_specs&lt; ParseContext::char_type &gt;',['../structbasic__format__specs.html',1,'']]],
  ['basic_5fmemory_5fbuffer',['basic_memory_buffer',['../classbasic__memory__buffer.html',1,'basic_memory_buffer&lt; T, SIZE, Allocator &gt;'],['../classbasic__memory__buffer.html#a981f02b3da4bdd36d32c065369c66f7d',1,'basic_memory_buffer::basic_memory_buffer()']]],
  ['basic_5fmemory_5fbuffer_3c_20char_20_3e',['basic_memory_buffer&lt; Char &gt;',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fparse_5fcontext',['basic_parse_context',['../classbasic__parse__context.html',1,'']]],
  ['basic_5fparse_5fcontext_3c_20char_20_3e',['basic_parse_context&lt; Char &gt;',['../classbasic__parse__context.html',1,'']]],
  ['basic_5fparse_5fcontext_3c_20char_5ftype_20_3e',['basic_parse_context&lt; char_type &gt;',['../classbasic__parse__context.html',1,'']]],
  ['basic_5fprintf_5fcontext',['basic_printf_context',['../classbasic__printf__context.html',1,'basic_printf_context&lt; OutputIt, Char &gt;'],['../classbasic__printf__context.html#a70fcf45d0076835d464b8f3fb0cd4e1c',1,'basic_printf_context::basic_printf_context()']]],
  ['basic_5fstring_5fview',['basic_string_view',['../classbasic__string__view.html',1,'basic_string_view&lt; Char &gt;'],['../classbasic__string__view.html#a30be409cd941f8fa06e5e7b27496e3dc',1,'basic_string_view::basic_string_view(const Char *s, size_t count) FMT_NOEXCEPT'],['../classbasic__string__view.html#a84823e4cf3eadc6bbe4ecd18e7685ffd',1,'basic_string_view::basic_string_view(const Char *s)'],['../classbasic__string__view.html#a26380481d5c1675f0f56333f764c496b',1,'basic_string_view::basic_string_view(const std::basic_string&lt; Char, Alloc &gt; &amp;s) FMT_NOEXCEPT']]],
  ['basic_5fstring_5fview_3c_20char_20_3e',['basic_string_view&lt; char &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5fstring_5fview_3c_20char8_5ft_20_3e',['basic_string_view&lt; char8_t &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5fstring_5fview_3c_20char_5ftype_20_3e',['basic_string_view&lt; char_type &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5fwriter',['basic_writer',['../classinternal_1_1basic__writer.html#a5779f775bf1c1051483f9abfb4b6eb53',1,'internal::basic_writer']]],
  ['basic_5fwriter',['basic_writer',['../classinternal_1_1basic__writer.html',1,'internal']]],
  ['bin_5fwriter',['bin_writer',['../structinternal_1_1basic__writer_1_1int__writer_1_1bin__writer.html',1,'internal::basic_writer::int_writer']]],
  ['binarybuffer',['BinaryBuffer',['../structdiy_1_1_binary_buffer.html',1,'diy']]],
  ['bits',['bits',['../structinternal_1_1bits.html',1,'internal']]],
  ['block',['block',['../structdiy_1_1_reduce_proxy.html#a6ae6c22da66bea79cbf2702a5d51fe2b',1,'diy::ReduceProxy']]],
  ['blockid',['BlockID',['../structdiy_1_1_block_i_d.html',1,'diy']]],
  ['bool_5fpack',['bool_pack',['../structinternal_1_1bool__pack.html',1,'internal']]],
  ['bounds',['Bounds',['../structdiy_1_1_bounds.html',1,'diy']]],
  ['boundsvalue',['BoundsValue',['../structdiy_1_1_bounds_value.html',1,'diy']]],
  ['bov',['BOV',['../classdiy_1_1io_1_1_b_o_v.html',1,'diy::io']]],
  ['broadcast',['broadcast',['../group___m_p_i.html#ga306425d8ccbecd1b6fd77ec0950c86a6',1,'diy::mpi::broadcast(const communicator &amp;comm, T &amp;x, int root)'],['../group___m_p_i.html#ga8fc285826a89324e72a1ccfb419c5662',1,'diy::mpi::broadcast(const communicator &amp;comm, std::vector&lt; T &gt; &amp;x, int root)']]],
  ['buffer',['buffer',['../classinternal_1_1buffer.html',1,'internal']]],
  ['buffer_3c_20char_20_3e',['buffer&lt; Char &gt;',['../classinternal_1_1buffer.html',1,'internal::buffer&lt; Char &gt;'],['../classinternal_1_1buffer.html',1,'internal::buffer&lt; char &gt;']]],
  ['buffer_3c_20container_3a_3avalue_5ftype_20_3e',['buffer&lt; Container::value_type &gt;',['../classinternal_1_1buffer.html',1,'internal']]],
  ['buffer_5frange',['buffer_range',['../classinternal_1_1buffer__range.html',1,'internal']]],
  ['buffered_5ffile',['buffered_file',['../classbuffered__file.html',1,'']]]
];
